kind: pipeline
type: docker
name: farmacia-ci

steps:
  - name: checkout
    image: alpine/git
    commands:
      - git fetch --all
      - git reset --hard origin/${DRONE_BRANCH}

  # ===== Backend =====
  - name: build-backend
    image: maven:3.9.9-eclipse-temurin-17
    when:
      exists:
        - pharmacy/pom.xml
        - backend/pom.xml
    commands:
      - cd pharmacy || cd backend
      - mvn clean install -B

  - name: test-backend
    image: maven:3.9.9-eclipse-temurin-17
    when:
      exists:
        - pharmacy/pom.xml
        - backend/pom.xml
    commands:
      - cd pharmacy || cd backend
      - mvn test -B

  - name: sonar-backend
    image: maven:3.9.9-eclipse-temurin-17
    environment:
      SONAR_HOST_URL: http://sonarqube:9000
      SONAR_TOKEN:
        from_secret: sonarqube-backend-${DRONE_BRANCH}
    when:
      branch:
        include: [ main, development, qa ]
      exists:
        - pharmacy/pom.xml
        - backend/pom.xml
    commands:
      - cd pharmacy || cd backend
      - mvn sonar:sonar \
          -Dsonar.projectKey=FP_Backend_${DRONE_BRANCH} \
          -Dsonar.projectName=FP_Backend_${DRONE_BRANCH} \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN

  # ===== Frontend =====
  - name: build-frontend
    image: node:18
    when:
      exists:
        - frontend/package.json
    commands:
      - cd frontend
      - npm install

  - name: test-frontend
    image: node:18
    when:
      exists:
        - frontend/package.json
    commands:
      - cd frontend
      - npm install
      - npm test -- --watch=false --code-coverage

  - name: sonar-frontend
    image: sonarsource/sonar-scanner-cli:latest
    environment:
      SONAR_HOST_URL: http://sonarqube:9000
      SONAR_TOKEN:
        from_secret: sonarqube-frontend-${DRONE_BRANCH}
    when:
      branch:
        include: [ main, development, qa ]
      exists:
        - frontend/package.json
    commands:
      - cd frontend
      - sonar-scanner \
          -Dsonar.projectKey=FP_Frontend_${DRONE_BRANCH} \
          -Dsonar.projectName=FP_Frontend_${DRONE_BRANCH} \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
