kind: pipeline
type: docker
name: farmacia-ci

workspace:
  base: /drone
  path: src

clone:
  depth: 50

steps:
  - name: checkout
    image: alpine/git
    commands:
      - git fetch --all
      - git reset --hard origin/${DRONE_BRANCH}

  # ===== Backend (build → test) =====
  - name: build-backend
    image: maven:3.9.9-eclipse-temurin-17
    when:
      exists: [ pharmacy/pom.xml ]
    environment:
      MAVEN_OPTS: -Dmaven.test.skip=true
    depends_on: [ checkout ]
    commands:
      - cd pharmacy
      - mvn -q -B clean install -DskipTests

  - name: test-backend
    image: maven:3.9.9-eclipse-temurin-17
    when:
      exists: [ pharmacy/pom.xml ]
    depends_on: [ build-backend ]
    commands:
      - cd pharmacy
      - mvn -q -B test jacoco:report

  # === Esperar SonarQube (público: /api/system/status) ===
  - name: wait-for-sonar
    image: curlimages/curl:8.9.1
    depends_on: [ test-backend ]
    environment:
      SONAR_HOST_URL:
        from_secret: sonar_host_url 
    commands:
      - |
        echo "Esperando $SONAR_HOST_URL ..."
        for i in $(seq 1 60); do
          if curl -fsS "$SONAR_HOST_URL/api/system/status" | grep -q '"status":"UP"'; then
            echo "SonarQube listo (status=UP)"; exit 0
          fi
          sleep 5
        done
        echo "Timeout esperando SonarQube (status!=UP)"; exit 8

  # ===== Sonar BACKEND por rama =====
  - name: sonar-backend-main
    image: maven:3.9.9-eclipse-temurin-17
    when:
      branch: [ main ]
      exists: [ pharmacy/pom.xml ]
    environment:
      SONAR_HOST_URL:
        from_secret: sonar_host_url
      SONAR_TOKEN:
        from_secret: sonar_token_backend_main
    depends_on: [ wait-for-sonar ]
    commands:
      - test -n "$SONAR_HOST_URL" || { echo "Falta secreto sonar_host_url"; exit 2; }
      - test -n "$SONAR_TOKEN" || { echo "Falta secreto sonar_token_backend_main"; exit 2; }
      - cd pharmacy
      - |
        mvn -B sonar:sonar \
          -DskipTests \
          -Dsonar.projectKey=FP:Backend_Prod \
          -Dsonar.projectName=FP:Backend_Prod \
          -Dsonar.host.url="$SONAR_HOST_URL" \
          -Dsonar.token="$SONAR_TOKEN" \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  - name: sonar-backend-development
    image: maven:3.9.9-eclipse-temurin-17
    when:
      branch: [ development ]
      exists: [ pharmacy/pom.xml ]
    environment:
      SONAR_HOST_URL:
        from_secret: sonar_host_url
      SONAR_TOKEN:
        from_secret: sonar_token_backend_development
    depends_on: [ wait-for-sonar ]
    commands:
      - test -n "$SONAR_HOST_URL" || { echo "Falta secreto sonar_host_url"; exit 2; }
      - test -n "$SONAR_TOKEN" || { echo "Falta secreto sonar_token_backend_development"; exit 2; }
      - cd pharmacy
      - |
        mvn -B sonar:sonar \
          -DskipTests \
          -Dsonar.projectKey=FP:Backend_Development \
          -Dsonar.projectName=FP:Backend_Development \
          -Dsonar.host.url="$SONAR_HOST_URL" \
          -Dsonar.token="$SONAR_TOKEN" \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  - name: sonar-backend-qa
    image: maven:3.9.9-eclipse-temurin-17
    when:
      branch: [ qa ]
      exists: [ pharmacy/pom.xml ]
    environment:
      SONAR_HOST_URL:
        from_secret: sonar_host_url
      SONAR_TOKEN:
        from_secret: sonar_token_backend_qa
    depends_on: [ wait-for-sonar ]
    commands:
      - test -n "$SONAR_HOST_URL" || { echo "Falta secreto sonar_host_url"; exit 2; }
      - test -n "$SONAR_TOKEN" || { echo "Falta secreto sonar_token_backend_qa"; exit 2; }
      - cd pharmacy
      - |
        mvn -B sonar:sonar \
          -DskipTests \
          -Dsonar.projectKey=FP:Backend_Qa \
          -Dsonar.projectName=FP:Backend_Qa \
          -Dsonar.host.url="$SONAR_HOST_URL" \
          -Dsonar.token="$SONAR_TOKEN" \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  # ===== Frontend (build → test) =====
  - name: build-frontend
    image: node:18
    when:
      exists: [ frontend/package.json ]
    depends_on:
      - sonar-backend-main
      - sonar-backend-development
      - sonar-backend-qa
    commands:
      - cd frontend
      - npm ci
      - npm run build || true

  - name: test-frontend
    image: node:18-bullseye
    when:
      exists: [ frontend/package.json ]
    environment:
      CI: "true"                     # tu karma ya lo usa para singleRun/headless
      CHROME_BIN: /usr/bin/chromium  # para karma-chrome-launcher
    depends_on: [ build-frontend ]
    commands:
      - apt-get update
      - apt-get install -y chromium fonts-liberation libnss3 libasound2 libatk-bridge2.0-0 libgtk-3-0 libgbm1 xvfb
      - cd frontend
      # 1) intenta instalar “normal”, pero relajando peer deps (Angular viejo)
      - npm ci --no-audit --no-fund --legacy-peer-deps || {
          echo "Reintentando sin scripts (posible prepare/postinstall problem)"; 
          npm ci --no-audit --no-fund --legacy-peer-deps --ignore-scripts;
        }
      # 2) corre los tests en Chrome headless sin sandbox y con cobertura
      - npm test -- --watch=false --code-coverage

  # ===== Sonar FRONTEND por rama =====
  - name: sonar-frontend-main
    image: sonarsource/sonar-scanner-cli:latest
    when:
      branch: [ main ]
      exists: [ frontend/package.json ]
    environment:
      SONAR_HOST_URL:
        from_secret: sonar_host_url
      SONAR_TOKEN:
        from_secret: sonar_token_frontend_main
      SONAR_USER_HOME: /tmp/sonar         
    depends_on: [ test-frontend, wait-for-sonar ]
    commands:
      - test -n "$SONAR_HOST_URL" || { echo "Falta secreto sonar_host_url"; exit 2; }
      - test -n "$SONAR_TOKEN" || { echo "Falta secreto sonar_token_frontend_main"; exit 2; }
      - cd frontend
      - test -f coverage/lcov.info || { echo "No existe coverage/lcov.info"; ls -la coverage || true; exit 3; }
      - |
        sonar-scanner \
          -Dsonar.projectKey=FP:Frontend_Prod \
          -Dsonar.projectName=FP:Frontend_Prod \
          -Dsonar.sources=. \
          -Dsonar.host.url="$SONAR_HOST_URL" \
          -Dsonar.token="$SONAR_TOKEN" \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
          -Dsonar.working.directory=/tmp/.scannerwork \
          -Djava.io.tmpdir=/tmp

  - name: sonar-frontend-development
    image: sonarsource/sonar-scanner-cli:latest
    when:
      branch: [ development ]
      exists: [ frontend/package.json ]
    environment:
      SONAR_HOST_URL:
        from_secret: sonar_host_url
      SONAR_TOKEN:
        from_secret: sonar_token_frontend_development
      SONAR_USER_HOME: /tmp/sonar          
    depends_on: [ test-frontend, wait-for-sonar ]
    commands:
      - test -n "$SONAR_HOST_URL" || { echo "Falta secreto sonar_host_url"; exit 2; }
      - test -n "$SONAR_TOKEN" || { echo "Falta secreto sonar_token_frontend_development"; exit 2; }
      - cd frontend
      - test -f coverage/lcov.info || { echo "No existe coverage/lcov.info"; ls -la coverage || true; exit 3; }
      - mkdir -p .scannerwork && chmod -R 777 .scannerwork || true
      - |
        sonar-scanner \
          -Dsonar.projectKey=FP:Frontend_Development \
          -Dsonar.projectName=FP:Frontend_Development  \
          -Dsonar.sources=. \
          -Dsonar.host.url="$SONAR_HOST_URL" \
          -Dsonar.token="$SONAR_TOKEN" \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
          -Dsonar.working.directory=/tmp/.scannerwork \
          -Djava.io.tmpdir=/tmp

  - name: sonar-frontend-qa
    image: sonarsource/sonar-scanner-cli:latest
    when:
      branch: [ qa ]
      exists: [ frontend/package.json ]
    environment:
      SONAR_HOST_URL:
        from_secret: sonar_host_url
      SONAR_TOKEN:
        from_secret: sonar_token_frontend_qa
      SONAR_USER_HOME: /tmp/sonar
    depends_on: [ test-frontend, wait-for-sonar ]
    commands:
      - test -n "$SONAR_HOST_URL" || { echo "Falta secreto sonar_host_url"; exit 2; }
      - test -n "$SONAR_TOKEN" || { echo "Falta secreto sonar_token_frontend_qa"; exit 2; }
      - cd frontend
      - mkdir -p .scannerwork && chmod -R 777 .scannerwork || true
      - test -f coverage/lcov.info || { echo "No existe coverage/lcov.info"; ls -la coverage || true; exit 3; }
      - |
        sonar-scanner \
          -Dsonar.projectKey=FP:Frontend_Qa \
          -Dsonar.projectName=FP:Frontend_Qa \
          -Dsonar.sources=. \
          -Dsonar.host.url="$SONAR_HOST_URL" \
          -Dsonar.token="$SONAR_TOKEN" \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
          -Dsonar.working.directory=/tmp/.scannerwork \
          -Djava.io.tmpdir=/tmp


# ===== Notificación: ÉXITO =====
  - name: notify-success
    image: plugins/email
    when:
      status: [ success ]
    settings:
      host: smtp.gmail.com
      port: 587
      username:
        from_secret: smtp_user
      password:
        from_secret: smtp_pass
      from: sandovalisabela0524@gmail.com
      recipients:
        - jflores@unis.edu.gt
        - abrilsofia159@gmail.com
      subject: "TEST EXITOSO"
      headers:
        - "Content-Type: text/html; charset=UTF-8"
      body: |
        <!doctype html>
        <html lang="es">
        <head>
          <meta charset="utf-8">
          <style>
            body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#f6f7fb;color:#111}
            .box{max-width:640px;margin:16px auto;background:#fff;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden}
            .head{padding:14px 18px;background:#16a34a;color:#fff;font-weight:700}
            .sub{padding:8px 18px;background:#ecfdf5;color:#065f46;font-size:12px}
            .content{padding:16px 18px}
            table{width:100%;border-collapse:collapse}
            td{padding:8px 6px;border-bottom:1px solid #f1f5f9;font-size:14px}
            td:first-child{color:#64748b;width:34%}
            .foot{padding:10px 18px;color:#64748b;font-size:12px;background:#fafafa}
          </style>
        </head>
        <body>
          <div class="box">
            <div class="head">Resultado del pipeline — Éxito</div>
            <div class="sub">Estado: <strong>${DRONE_BUILD_STATUS}</strong></div>
            <div class="content">
              <table>
                <tr><td>Proyecto</td><td>${DRONE_REPO}</td></tr>
                <tr><td>Rama</td><td>${DRONE_BRANCH}</td></tr>
                <tr><td>Build #</td><td>${DRONE_BUILD_NUMBER}</td></tr>
                <tr><td>Autor</td><td>${DRONE_COMMIT_AUTHOR}</td></tr>
                <tr><td>Commit</td><td>${DRONE_COMMIT_SHA}</td></tr>
              </table>
            </div>
            <div class="foot">Enviado automáticamente por Drone CI</div>
          </div>
        </body>
        </html>

  # ===== Notificación: FALLO =====
  - name: notify-failure
    image: plugins/email
    when:
      status: [ failure ]
    settings:
      host: smtp.gmail.com
      port: 587
      username:
        from_secret: smtp_user
      password:
        from_secret: smtp_pass
      from: sandovalisabela0524@gmail.com
      recipients:
        - jflores@unis.edu.gt
        - abrilsofia159@gmail.com
      subject: "TEST FALLIDO "
      headers:
        - "Content-Type: text/html; charset=UTF-8"
      body: |
        <!doctype html>
        <html lang="es">
        <head>
          <meta charset="utf-8">
          <style>
            body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#f6f7fb;color:#111}
            .box{max-width:640px;margin:16px auto;background:#fff;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden}
            .head{padding:14px 18px;background:#dc2626;color:#fff;font-weight:700}
            .sub{padding:8px 18px;background:#fef2f2;color:#7f1d1d;font-size:12px}
            .content{padding:16px 18px}
            table{width:100%;border-collapse:collapse}
            td{padding:8px 6px;border-bottom:1px solid #f1f5f9;font-size:14px}
            td:first-child{color:#64748b;width:34%}
            .foot{padding:10px 18px;color:#64748b;font-size:12px;background:#fafafa}
          </style>
        </head>
        <body>
          <div class="box">
            <div class="head">Resultado del pipeline — Fallo</div>
            <div class="sub">Estado: <strong>${DRONE_BUILD_STATUS}</strong></div>
            <div class="content">
              <table>
                <tr><td>Proyecto</td><td>${DRONE_REPO}</td></tr>
                <tr><td>Rama</td><td>${DRONE_BRANCH}</td></tr>
                <tr><td>Build #</td><td>${DRONE_BUILD_NUMBER}</td></tr>
                <tr><td>Autor</td><td>${DRONE_COMMIT_AUTHOR}</td></tr>
                <tr><td>Commit</td><td>${DRONE_COMMIT_SHA}</td></tr>
              </table>
            </div>
            <div class="foot">Enviado automáticamente por Drone CI</div>
          </div>
        </body>
        </html>
