version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-xe-qa-pharmacy
    environment:
      - ORACLE_PASSWORD=LocalOraclePass2
    ports:
      - "1524:1521"
    volumes:
      - ./oracle-data-qa:/opt/oracle/oradata
      - ./db-scripts:/docker-entrypoint-initdb.d
    networks:
      - pharmacy-network

  backend:
    build:
      context: ./pharmacy
      dockerfile: Dockerfile
    container_name: pharmacy-backend-qa
    ports:
      - "8083:8080"
    depends_on:
      - oracle-db
    restart: always
    networks:
      - pharmacy-network
    environment:
      SPRING_PROFILES_ACTIVE: qa

  frontend:
    build:
      context: ./frontend  # Ruta al frontend
      dockerfile: Dockerfile
      args:
        CONFIGURATION: qa  # Configuración para el build
    container_name: pharmacy-frontend-qa
    ports:
      - "4301:80"
    depends_on:
      - backend
    networks:
      - pharmacy-network

networks:
  pharmacy-network:
    external: true