version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-xe-prod-pharmacy
    environment:
      - ORACLE_PASSWORD=LocalOraclePass2
    ports:
      - "1525:1521"
    volumes:
      - ./oracle-data-prod:/opt/oracle/oradata
      - ./db-scripts:/docker-entrypoint-initdb.d
    user: "54321:54321"
    networks:
      - pharmacy-network

  backend:
    build:
      context: ./pharmacy
      dockerfile: Dockerfile
    container_name: pharmacy-backend-prod
    ports:
      - "8085:8080"
    depends_on:
      - oracle-db
    restart: always
    networks:
      - pharmacy-network
    environment:
      SPRING_PROFILES_ACTIVE: prod

  frontend:
    build:
      context: ./frontend  # Ruta al frontend
      dockerfile: Dockerfile
      args:
        CONFIGURATION: production # Configuración para el build
    container_name: pharmacy-frontend-prod
    ports:
      - "4305:80"
    depends_on:
      - backend
    networks:
      - pharmacy-network

networks:
  pharmacy-network:
    external: true