version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-xe-dev-pharmacy
    environment:
      - ORACLE_PASSWORD=LocalOraclePass2
    ports:
      - "1523:1521"
    volumes:
      - /home/sofi/Documents/GitHub/farmacia-proyecto/oracle-data-dev:/opt/oracle/oradata
      - ./db-scripts:/docker-entrypoint-initdb.d
    networks:
      - pharmacy-network

  backend:
    build:
      context: ./pharmacy
      dockerfile: Dockerfile
    container_name: pharmacy-backend-dev
    ports:
      - "8082:8080"
    depends_on:
      - oracle-db
    restart: always
    networks:
      - pharmacy-network
    environment:
      SPRING_PROFILES_ACTIVE: dev

  frontend:
    build:
      context: ./frontend  # Ruta al frontend
      dockerfile: Dockerfile
      args:
        CONFIGURATION: development  # Configuración para el build
    container_name: pharmacy-frontend-dev
    ports:
      - "4300:80"
    depends_on:
      - backend
    networks:
      - pharmacy-network

networks:
  pharmacy-network:
    external: true