services:

  drone-server:
    image: drone/drone:2
    container_name: drone-server
    restart: always
    ports:
      - "8085:80"                
    environment:
      DRONE_SERVER_HOST: c01f99367744.ngrok-free.app
      DRONE_SERVER_PROTO: https
      DRONE_RPC_SECRET: carmasof
      DRONE_ADMIN_USER: sofi
      DRONE_GITHUB_CLIENT_ID: Ov23li69e8xq8ohUphMF
      DRONE_GITHUB_CLIENT_SECRET: 2a8dc1a3f15e4f5494dc7a96bbd9d5a2f4398d61
      DRONE_GITHUB_SERVER: https://github.com
      DRONE_USER_CREATE: username:sofi,admin:true
      DRONE_LOGS_DEBUG: "true"
    volumes:
      - ./drone-data:/data       
    networks:
      - pharmacy-network

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    restart: always
    environment:
      DRONE_RPC_PROTO: https
      DRONE_RPC_HOST: c01f99367744.ngrok-free.app
      DRONE_RPC_SECRET: carmasof
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: runner-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pharmacy-network

networks:
  pharmacy-network:
    external: true
