ALTER SESSION SET CONTAINER = XEPDB1;

DECLARE
  v_open NUMBER;
BEGIN
  FOR i IN 1..60 LOOP  -- Wait up to 60 seconds
    SELECT COUNT(*) INTO v_open FROM v$pdbs WHERE name = 'XEPDB1' AND open_mode = 'READ WRITE';
    EXIT WHEN v_open = 1;
    DBMS_LOCK.SLEEP(1);  -- Wait 1 second
  END LOOP;
END;
/

-- ===============================================
-- Crear usuarios PHARMACY_DEV, PHARMACY_QA, PHARMACY_PROD
-- ===============================================
BEGIN
   DECLARE
      v_count NUMBER;
   BEGIN
      -- DEV
      SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'PHARMACY_DEV';
      IF v_count = 0 THEN
         EXECUTE IMMEDIATE 'CREATE USER PHARMACY_DEV IDENTIFIED BY devpass';
         EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO PHARMACY_DEV';
         EXECUTE IMMEDIATE 'ALTER USER PHARMACY_DEV QUOTA UNLIMITED ON USERS';
      END IF;

      -- QA
      SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'PHARMACY_QA';
      IF v_count = 0 THEN
         EXECUTE IMMEDIATE 'CREATE USER PHARMACY_QA IDENTIFIED BY qapass';
         EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO PHARMACY_QA';
         EXECUTE IMMEDIATE 'ALTER USER PHARMACY_QA QUOTA UNLIMITED ON USERS';
      END IF;

      -- PROD
      SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'PHARMACY_PROD';
      IF v_count = 0 THEN
         EXECUTE IMMEDIATE 'CREATE USER PHARMACY_PROD IDENTIFIED BY prodpass';
         EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO PHARMACY_PROD';
         EXECUTE IMMEDIATE 'ALTER USER PHARMACY_PROD QUOTA UNLIMITED ON USERS';
      END IF;
   END;
END;
/
