ALTER SESSION SET CONTAINER = XEPDB1;

DECLARE
  v_open NUMBER;
BEGIN
  FOR i IN 1..60 LOOP  -- Wait up to 60 seconds
    SELECT COUNT(*) INTO v_open FROM v$pdbs WHERE name = 'XEPDB1' AND open_mode = 'READ WRITE';
    EXIT WHEN v_open = 1;
    DBMS_LOCK.SLEEP(1);  -- Wait 1 second
  END LOOP;
END;
/

--------------------------------------------------
-- 1. Crear schemas si no existen
--------------------------------------------------
BEGIN
   -- DEV
   IF NOT EXISTS (SELECT 1 FROM dba_users WHERE username = 'PHARMACY_DEV') THEN
      EXECUTE IMMEDIATE 'CREATE USER PHARMACY_DEV IDENTIFIED BY devpass';
      EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO PHARMACY_DEV';
      EXECUTE IMMEDIATE 'ALTER USER PHARMACY_DEV QUOTA UNLIMITED ON USERS';
   END IF;

   -- QA
   IF NOT EXISTS (SELECT 1 FROM dba_users WHERE username = 'PHARMACY_QA') THEN
      EXECUTE IMMEDIATE 'CREATE USER PHARMACY_QA IDENTIFIED BY qapass';
      EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO PHARMACY_QA';
      EXECUTE IMMEDIATE 'ALTER USER PHARMACY_QA QUOTA UNLIMITED ON USERS';
   END IF;

   -- PROD
   IF NOT EXISTS (SELECT 1 FROM dba_users WHERE username = 'PHARMACY_PROD') THEN
      EXECUTE IMMEDIATE 'CREATE USER PHARMACY_PROD IDENTIFIED BY prodpass';
      EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO PHARMACY_PROD';
      EXECUTE IMMEDIATE 'ALTER USER PHARMACY_PROD QUOTA UNLIMITED ON USERS';
   END IF;
END;
/
