ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = PHARMACY_LOCAL;

CREATE TABLE CARRITO (
    id_cart               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario            NUMBER NOT NULL,
    status                CHAR(1) DEFAULT 'A' CHECK (status IN ('A', 'C', 'X')),  
    fecha_creacion        TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_actualizacion   TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_cart_usuario FOREIGN KEY (id_usuario) REFERENCES Usuario(id_usuario)
);

CREATE TABLE CARRITO_DETALLE (
    id_cart_item     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cart          NUMBER NOT NULL,
    id_medicamento   NUMBER NOT NULL,
    cantidad         NUMBER NOT NULL CHECK (cantidad > 0),
    precio_unitario  NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_cart_item_cart FOREIGN KEY (id_cart) REFERENCES Carrito(id_cart),
    CONSTRAINT fk_cart_item_medicamento FOREIGN KEY (id_medicamento) REFERENCES Medicamento(id_medicamento)
);

CREATE TABLE PAGINA  (
    id_pagina         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo            VARCHAR2(200) NOT NULL,
    slug              VARCHAR2(100) UNIQUE NOT NULL,  
    contenido         CLOB,                          
    tipo_pagina       VARCHAR2(50) NOT NULL,          
    estado            VARCHAR2(20) DEFAULT 'BORRADOR' CHECK (estado IN ('BORRADOR', 'PUBLICADO', 'RECHAZADO')),
    fecha_creacion    TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    id_autor          NUMBER,                         
    visible           CHAR(1) DEFAULT 'N' CHECK (visible IN ('Y', 'N')),            
    CONSTRAINT fk_pagina_usuario FOREIGN KEY (id_autor) REFERENCES Usuario(id_usuario)
);

CREATE TABLE NAV_ITEM (
    id_nav_item      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pagina        NUMBER,                    
    etiqueta         VARCHAR2(100) NOT NULL,    
    path              VARCHAR2(200),             
    orden            NUMBER,                    
    activo           CHAR(1) DEFAULT 'Y',       
    CONSTRAINT fk_nav_item_pagina FOREIGN KEY (id_pagina) REFERENCES Pagina(id_pagina)
);

CREATE TABLE PAGE_MODIFICATION  (
    id_modificacion   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pagina         NUMBER,                          
    contenido_nuevo   CLOB,                            
    comentario        VARCHAR2(500),                   
    estado            VARCHAR2(20) DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE', 'APROBADO', 'RECHAZADO')),
    fecha_modificacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    id_editor         NUMBER NOT NULL,                 
    id_moderador      NUMBER,                          
    CONSTRAINT fk_modif_pagina FOREIGN KEY (id_pagina) REFERENCES Pagina(id_pagina),
    CONSTRAINT fk_modif_editor FOREIGN KEY (id_editor) REFERENCES Usuario(id_usuario),
    CONSTRAINT fk_modif_moderador FOREIGN KEY (id_moderador) REFERENCES Usuario(id_usuario)
);

CREATE OR REPLACE TRIGGER TR_UPDATE_CARRITO_TIMESTAMP
BEFORE UPDATE ON CARRITO
FOR EACH ROW
BEGIN
    :NEW.fecha_actualizacion := SYSTIMESTAMP;
END;
/

COMMIT; 
